# Code generated by Google Gemini
# -WindowStyle Hidden -ExecutionPolicy Bypass -File "E:\GitHub\game\script\snowbreak\AutoDownloadRelease.ps1"
# ================= 配置区域 =================
$RepoOwner = "ahalpha"        # 例如 "microsoft"
$RepoName = "Snowbreak-AnitAmend"          # 例如 "vscode"
$DownloadDir = "F:\Downloads\GitHubReleases"  # 下载保存的文件夹
$TargetExtension = ".pak"    # 你想要下载的文件后缀，例如 .zip, .exe, .tar.gz
# 【新增】你想要自动复制到的目标目录列表 (用逗号分隔，可以写两个或更多)
$TargetDirs = @(
    "G:\SeasunCBJQos\Game\cbjq\game\Game\Content\Paks",
    "G:\Steam\steamapps\common\SNOWBREAK\Game\Content\Paks"
)

$WebhookUrl = ""
# ============================================

# 初始化主下载目录 (提前初始化以便存放日志)
if (!(Test-Path -Path $DownloadDir)) { New-Item -ItemType Directory -Path $DownloadDir | Out-Null }

# ================= 日志函数 =================
$LogFile = Join-Path -Path $DownloadDir -ChildPath "script_log.txt"
Function Write-Log {
    param([string]$Message)
    $LogEntry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] $Message"
    # 同时输出到控制台（如果手动运行的话可见）和日志文件
    Write-Host $LogEntry 
    $LogEntry | Out-File -FilePath $LogFile -Append -Encoding utf8
}
# ============================================

Write-Log "========== 脚本开始执行 =========="

# 【提速优化 1】关闭极其拖慢速度的 PowerShell 下载进度条
$ProgressPreference = 'SilentlyContinue'

# 【提速优化 2】强制 PowerShell 使用系统的全局代理
# 定义你真实的代理地址
# $MyProxy = "http://127.0.0.1:17890"
# $WebProxy = New-Object System.Net.WebProxy("http://127.0.0.1:17890")
[System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebRequest]::GetSystemWebProxy()
# [System.Net.WebRequest]::DefaultWebProxy = $WebProxy
[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
Write-Log "已配置全局代理设置"

# 1. 网络连通性检查 (最多等2分钟)
# 修复：api.github.com 可能禁 ping，改用 Test-NetConnection 测试 443 端口
Write-Log "正在检查与 api.github.com 的网络连接..."
$maxWait = 120
$waited = 0
$isConnected = $false
while (-not $isConnected -and $waited -lt $maxWait) {
    # Quiet 参数返回布尔值，测试 TCP 443 端口是否连通
    $isConnected = (Test-NetConnection -ComputerName "api.github.com" -Port 443 -WarningAction SilentlyContinue).TcpTestSucceeded
    if (-not $isConnected) {
        Start-Sleep -Seconds 5
        $waited += 5
    }
}

if (-not $isConnected) { 
    Write-Log "【错误】等待 120 秒后仍无法连接到 api.github.com，脚本退出。"
    exit 
}
Write-Log "网络连接成功，耗时 $waited 秒。"

$VersionFile = Join-Path -Path $DownloadDir -ChildPath "latest_version.txt"
$ApiUrl = "https://api.github.com/repos/$RepoOwner/$RepoName/releases/latest"

try {
    # 2. 获取 GitHub 最新信息
    Write-Log "正在请求 GitHub API: $ApiUrl"
    $Response = Invoke-RestMethod -Uri $ApiUrl -Method Get -ErrorAction Stop -Proxy $MyProxy
    $LatestVersion = $Response.tag_name
    Write-Log "成功获取最新版本号: $LatestVersion"

    # 获取需要处理的文件列表 (Asset)
    if ([string]::IsNullOrWhiteSpace($TargetExtension)) {
        $Assets = $Response.assets
    } else {
        $Assets = $Response.assets | Where-Object { $_.name -like "*$TargetExtension" }
    }

    if ($Assets.Count -eq 0) { 
        Write-Log "【提示】未找到后缀为 $TargetExtension 的文件，脚本退出。"
        exit 
    }
    Write-Log "找到匹配的文件数量: $($Assets.Count)"

    # 3. 检查主下载目录是否需要下载
    $CurrentVersion = $null
    if (Test-Path $VersionFile) { 
        $CurrentVersion = Get-Content -Path $VersionFile -TotalCount 1 
        Write-Log "本地主目录当前版本号: $CurrentVersion"
    } else {
        Write-Log "本地主目录无版本记录，准备首次下载。"
    }
    
    $IsDownloadedNow = $false

    if ($LatestVersion -ne $CurrentVersion) {
        Write-Log "版本不一致 ($LatestVersion != $CurrentVersion)，开始下载..."
        $VersionData = @($LatestVersion)

        foreach ($Asset in $Assets) {
            $DownloadUrl = $Asset.browser_download_url
            $FilePath = Join-Path -Path $DownloadDir -ChildPath $Asset.name
            
            Write-Log "正在下载: $($Asset.name) -> $FilePath"
            Invoke-WebRequest -Uri $DownloadUrl -OutFile $FilePath -Proxy $MyProxy

            if (Test-Path $FilePath) {
                Write-Log "下载完成，正在计算 SHA256..."
                $FileHash = (Get-FileHash -Path $FilePath -Algorithm SHA256).Hash
                $VersionData += "$($Asset.name) | $FileHash"
                Write-Log "校验完成: $FileHash"
            } else {
                Write-Log "【错误】下载失败，未找到文件: $FilePath"
            }
        }
        
        $VersionData | Out-File -FilePath $VersionFile -Encoding utf8
        $IsDownloadedNow = $true
        Write-Log "主目录更新完成并已写入 latest_version.txt"
    } else {
        Write-Log "主目录已是最新版本 ($LatestVersion)，跳过下载。"
    }

    # 4. ====== 分发复制逻辑 ======
    $CopiedAny = $false
    
    foreach ($TargetDir in $TargetDirs) {
        Write-Log "开始处理目标目录: $TargetDir"
        if (!(Test-Path -Path $TargetDir)) { 
            New-Item -ItemType Directory -Path $TargetDir | Out-Null
            Write-Log "目标目录不存在，已创建。"
        }
        
        $TargetVersionFile = Join-Path -Path $TargetDir -ChildPath "deploy_version.txt"
        $TargetVersion = $null
        if (Test-Path $TargetVersionFile) { 
            $TargetVersion = Get-Content -Path $TargetVersionFile -TotalCount 1 
            Write-Log "目标目录当前版本: $TargetVersion"
        }

        if ($LatestVersion -ne $TargetVersion) {
            Write-Log "目标目录需要更新，开始复制文件..."
            $TargetVersionData = @($LatestVersion)

            foreach ($Asset in $Assets) {
                $SourcePath = Join-Path -Path $DownloadDir -ChildPath $Asset.name
                $DestPath = Join-Path -Path $TargetDir -ChildPath $Asset.name
                
                if (Test-Path $SourcePath) {
                    Write-Log "正在复制: $SourcePath -> $DestPath"
                    Copy-Item -Path $SourcePath -Destination $DestPath -Force
                    
                    if (Test-Path $DestPath) {
                        Write-Log "复制完成，计算目标文件 SHA256..."
                        $DestFileHash = (Get-FileHash -Path $DestPath -Algorithm SHA256).Hash
                        $TargetVersionData += "$($Asset.name) | $DestFileHash"
                    }
                } else {
                    Write-Log "【警告】源文件不存在，无法复制: $SourcePath"
                }
            }
            
            $TargetVersionData | Out-File -FilePath $TargetVersionFile -Encoding utf8
            $CopiedAny = $true
            Write-Log "目标目录 $TargetDir 更新完成。"
        } else {
            Write-Log "目标目录已是最新版本，跳过复制。"
        }
    }

    # 5. 调用 Windows 通知中心
    if ($IsDownloadedNow -or $CopiedAny) {
        Write-Log "准备发送 Windows 系统通知..."
        $Message = "$RepoName $LatestVersion 处理完毕！`n"
        if ($IsDownloadedNow) { $Message += "√ 已下载并校验存入主目录`n" }
        if ($CopiedAny) { $Message += "√ 已分发并校验存入目标目录" }
        
        Add-Type -AssemblyName System.Windows.Forms
        $NotifyIcon = New-Object System.Windows.Forms.NotifyIcon
        $NotifyIcon.Icon = [System.Drawing.SystemIcons]::Information
        $NotifyIcon.Visible = $true
        
        $NotifyIcon.ShowBalloonTip(10000, "GitHub 更新通知", $Message, [System.Windows.Forms.ToolTipIcon]::Info)
        
        Start-Sleep -Seconds 5
        $NotifyIcon.Dispose()
        Write-Log "Windows 通知发送完毕。"
        
        if ($WebhookUrl) {
            Write-Log "触发 Webhook 推送..."
            # 这里可以放你的 Webhook 推送代码
        }
    }

    Write-Log "========== 脚本执行完毕 ==========`n"

} catch {
    # 修复了原本指定的 ErrorLogFile 是个文件夹路径的问题
    Write-Log "【严重错误】发生未捕获的异常: $($_.Exception.Message)"
    Write-Log "错误详情: $($_.InvocationInfo.PositionMessage)"
}