# Code generated by Google Gemini
# ================= 配置区域 =================
$RepoOwner = "ahalpha"        # 例如 "microsoft"
$RepoName = "Snowbreak-AnitAmend"          # 例如 "vscode"
$DownloadDir = "F:\Downloads\GitHubReleases"  # 下载保存的文件夹
$TargetExtension = ".pak"    # 你想要下载的文件后缀，例如 .zip, .exe, .tar.gz
# 【新增】你想要自动复制到的目标目录列表 (用逗号分隔，可以写两个或更多)
$TargetDirs = @(
    "G:\SeasunCBJQos\Game\cbjq\game\Game\Content\Paks",
    "G:\Steam\steamapps\common\SNOWBREAK\Game\Content\Paks"
)

$WebhookUrl = ""
# ============================================
# 1. 网络连通性检查 (最多等2分钟)
$maxWait = 120
$waited = 0
while (!(Test-Connection -ComputerName "api.github.com" -Count 1 -Quiet) -and $waited -lt $maxWait) {
    Start-Sleep -Seconds 5
    $waited += 5
}
if ($waited -ge $maxWait) { exit }

# 初始化主下载目录
if (!(Test-Path -Path $DownloadDir)) { New-Item -ItemType Directory -Path $DownloadDir | Out-Null }
$VersionFile = Join-Path -Path $DownloadDir -ChildPath "latest_version.txt"
$ApiUrl = "https://api.github.com/repos/$RepoOwner/$RepoName/releases/latest"

try {
    # 2. 获取 GitHub 最新信息
    $Response = Invoke-RestMethod -Uri $ApiUrl -Method Get -ErrorAction Stop
    $LatestVersion = $Response.tag_name

    # 获取需要处理的文件列表 (Asset)
    if ([string]::IsNullOrWhiteSpace($TargetExtension)) {
        $Assets = $Response.assets
    } else {
        $Assets = $Response.assets | Where-Object { $_.name -like "*$TargetExtension" }
    }

    if ($Assets.Count -eq 0) { exit }

    # 3. 检查主下载目录是否需要下载
    $CurrentVersion = $null
    if (Test-Path $VersionFile) { 
        # 只读取第一行作为版本号
        $CurrentVersion = Get-Content -Path $VersionFile -TotalCount 1 
    }
    
    $IsDownloadedNow = $false

    if ($LatestVersion -ne $CurrentVersion) {
        # 初始化要写入记录文件的数据，第一行放版本号
        $VersionData = @($LatestVersion)

        foreach ($Asset in $Assets) {
            $DownloadUrl = $Asset.browser_download_url
            $FilePath = Join-Path -Path $DownloadDir -ChildPath $Asset.name
            
            # 执行下载
            Invoke-WebRequest -Uri $DownloadUrl -OutFile $FilePath

            # 计算下载文件的 SHA256，并记录
            if (Test-Path $FilePath) {
                $FileHash = (Get-FileHash -Path $FilePath -Algorithm SHA256).Hash
                $VersionData += "$($Asset.name) | $FileHash"
            }
        }
        
        # 将版本号和哈希记录写入文件
        $VersionData | Out-File -FilePath $VersionFile -Encoding utf8
        $IsDownloadedNow = $true
    }

    # 4. ====== 分发复制逻辑 ======
    $CopiedAny = $false
    
    foreach ($TargetDir in $TargetDirs) {
        if (!(Test-Path -Path $TargetDir)) { New-Item -ItemType Directory -Path $TargetDir | Out-Null }
        
        $TargetVersionFile = Join-Path -Path $TargetDir -ChildPath "deploy_version.txt"
        $TargetVersion = $null
        if (Test-Path $TargetVersionFile) { 
            # 只读取第一行作为版本号
            $TargetVersion = Get-Content -Path $TargetVersionFile -TotalCount 1 
        }

        if ($LatestVersion -ne $TargetVersion) {
            # 初始化要写入目标目录记录文件的数据，第一行放版本号
            $TargetVersionData = @($LatestVersion)

            foreach ($Asset in $Assets) {
                $SourcePath = Join-Path -Path $DownloadDir -ChildPath $Asset.name
                $DestPath = Join-Path -Path $TargetDir -ChildPath $Asset.name
                
                if (Test-Path $SourcePath) {
                    # 执行覆盖复制
                    Copy-Item -Path $SourcePath -Destination $DestPath -Force
                    
                    # 在目标目录计算复制后文件的 SHA256，确保复制成功且文件完整
                    if (Test-Path $DestPath) {
                        $DestFileHash = (Get-FileHash -Path $DestPath -Algorithm SHA256).Hash
                        $TargetVersionData += "$($Asset.name) | $DestFileHash"
                    }
                }
            }
            
            # 将版本号和哈希记录写入目标目录的 deploy_version.txt
            $TargetVersionData | Out-File -FilePath $TargetVersionFile -Encoding utf8
            $CopiedAny = $true
        }
    }

    # 5. 调用 Windows 通知中心
    if ($IsDownloadedNow -or $CopiedAny) {
        $Message = "$RepoName $LatestVersion 处理完毕！`n"
        if ($IsDownloadedNow) { $Message += "√ 已下载并校验存入主目录`n" }
        if ($CopiedAny) { $Message += "√ 已分发并校验存入目标目录" }
        
        Add-Type -AssemblyName System.Windows.Forms
        $NotifyIcon = New-Object System.Windows.Forms.NotifyIcon
        $NotifyIcon.Icon = [System.Drawing.SystemIcons]::Information
        $NotifyIcon.Visible = $true
        
        $NotifyIcon.ShowBalloonTip(10000, "GitHub 更新通知", $Message, [System.Windows.Forms.ToolTipIcon]::Info)
        
        Start-Sleep -Seconds 5
        $NotifyIcon.Dispose()
        
        if ($WebhookUrl) {
            # 这里可以放你的 Webhook 推送代码
        }
    }

} catch {
    # 静默处理错误，不打扰用户
}